project_name: inbucket

release:
  github:
    owner: inbucket
    name: inbucket
  name_template: '{{.Tag}}'

brew:
  commit_author:
    name: goreleaserbot
    email: goreleaser@carlosbecker.com
  install: bin.install ""

before:
  hooks:
    - go mod download

builds:
  - binary: inbucket
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - freebsd
      - linux
      - windows
    goarch:
      - amd64
    goarm:
      - "6"
    main: ./cmd/inbucket
    ldflags: -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}
  - binary: inbucket-client
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - freebsd
      - linux
      - windows
    goarch:
      - amd64
    goarm:
      - "6"
    main: ./cmd/client
    ldflags: -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}

archive:
  format: tar.gz
  wrap_in_directory: true
  name_template: '{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{
    .Arm }}{{ end }}'
  format_overrides:
    - goos: windows
      format: zip
  files:
    - LICENSE*
    - README*
    - CHANGELOG*
    - etc/**/*
    - ui/dist/**/*
    - ui/greeting.html

nfpm:
  vendor: inbucket.org
  homepage: https://www.inbucket.org/
  maintainer: github@hillyerd.com
  description: All-in-one disposable webmail service.
  license: MIT
  formats:
    - deb
    - rpm
  files:
    "ui/dist/**/*": "/usr/local/share/inbucket/ui"
  config_files:
    "etc/linux/inbucket.service": "/lib/systemd/system/inbucket.service"
    "ui/greeting.html": "/etc/inbucket/greeting.html"

snapshot:
  name_template: SNAPSHOT-{{ .Commit }}

checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_checksums.txt'

dist: dist

sign:
  artifacts: none
