language: go
sudo: false

addons:
  apt:
    packages:
      - rpm

env:
  global:
    - GO111MODULE=on
    - DEPLOY_WITH_MAJOR="1.11"

before_script:
  - go get golang.org/x/lint/golint
  - make deps

go:
  - "1.10.x"
  - "1.11.x"

deploy:
  provider: script
  script: etc/travis-deploy.sh
  on:
    tags: true
